
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 18
y = 14

[scrolling]
history = 15000

[font]
size = 12

[font.normal]
family = "SauceCodePro NFM" #"Red Hat Mono" #"Source Code Pro"
style = "Regular"

[font.italic]
family = "SauceCodePro NFM" #"Red Hat Mono" #"Source Code Pro"
style = "Regular Italic"

[font.bold]
family = "SauceCodePro NFM" #"Red Hat Mono" # "Source Code Pro" 
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NFM" #"Red Hat Mono" # "Source Code Pro" 
style = "Bold Italic"

[general]
# This is the config file for alacritty terminal emulator

live_config_reload = true

import = [
    # choose a theme at https://github.com/alacritty/alacritty-theme
    # "~/.config/alacritty/themes/themes/dracula.toml"
    # "~/.config/alacritty/themes/themes/material_theme.toml"
    # "~/.config/alacritty/themes/themes/oceanic_next.toml"
    "~/.config/alacritty/themes/themes/zenburn.toml"
]



